[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.8",
    "openai>=1.64.0",
    "requests>=2.32.3",
    "uvicorn>=0.34.0",
]
